"""Promotion and marketing agent node for generating referral links, materials, and AI posters."""
import os
import json
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent
from langchain_mcp_adapters.client import MultiServerMCPClient
from typing import Dict, Any

from core.workflow.state import AgentState
from agents.billing_agent import UserIdInjector # Reuse the security interceptor to prevent unauthorized actions

class PromotionAgentNode:
    """
    Promotion Agent: handles requests for product sharing, referral commissions,
    campaign queries, and marketing-material retrieval.
    All tool calls fetch data from the backend marketing system via FastMCP.
    """
    def __init__(self):
        dotenv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), '.env')
        load_dotenv(dotenv_path)

        self.llm = ChatOpenAI(
            api_key=os.getenv("OPENAI_API_KEY"),
            model=os.getenv("MODEL", "gpt-4o"),
            base_url=os.getenv("BASE_URL") or None,
            temperature=0.3, # Marketing copy can afford a touch of creativity
        )
        
        from config.mcp_loader import load_mcp_servers_config
        self.servers_config = load_mcp_servers_config()

    async def _ensure_tools(self):
        pass

    async def __call__(self, state: AgentState) -> Dict[str, Any]:
        config = {"configurable": {"user_id": state.get("user_id", "unknown")}}
        
        # Re-initialize the MCP client on each call to avoid using the unsupported `async with`
        # ================== TODO 12 - Promotion tool set ==================
        # GOAL : Give the promotion agent its 4 marketing tools.
        # WHY  : Widest toolset in the project - shows how the allowlist scales per role.
        # STEPS:
        #   1. Same client construction as TODO 08/09.
        #   2. Filter to: get_promotable_products, search_product_catalog, get_promotion_materials, generate_ai_poster.
        # HINT : generate_ai_poster is slow (tens of seconds) - that is expected, not a hang.
        # CHECK: Ask 'I want to promote a product' - it should list products FIRST, not generate.
        # SIZE : ~6 lines
        # ======================================================

        memory_context = state.get("memory_context", "")
        
        system_prompt = f"""You are an enthusiastic cloud-platform [Promotion & Marketing Agent].
Your primary task is to help users who want to share or promote cloud products by providing product highlights, exclusive referral links, and AI-generated promotional posters.

Workflow:
1. **Intent: just browsing / list products**: When the user says "I want to promote a product", "what products can I promote", or "I want to earn money", you MUST **first call `get_promotable_products`** to retrieve the complete list of currently promotable products, display it to the user (numbered), and guide them to make a selection. **Do NOT call any material-generation tools yet — wait for the user's reply.**
2. **Intent: a specific product has been chosen**: When the user selects an item from the previous list (e.g., "I'll promote #1", "choose GPU"), or when the user immediately specifies a product (e.g., "Cloud Server ECS Standard Edition"):
   - You MUST **first call `search_product_catalog`** with the keyword or product name corresponding to the user's choice to obtain the standardized `product_id`.
3. **Handling not-found cases**:
   - If `search_product_catalog` returns `status: not_found`, **do NOT fabricate a product**!
   - Honestly tell the user that no dedicated single-product campaign exists for that item at this time, and recommend the generic campaign returned by the tool (e.g., `P_ALL_000`).
4. **Fetching precise materials and generating a poster**:
   - After obtaining a valid `product_id`, call `get_promotion_materials` to retrieve the exclusive link and selling points.
   - **Immediately after, call `generate_ai_poster`**, crafting a rich English or Chinese prompt based on the product's selling points and characteristics (e.g., "A futuristic cloud server room, glowing blue neon lights, high tech, 9:16 aspect ratio") to have the system generate a portrait-orientation promotional poster. Since image generation may take tens of seconds, naturally reassure the user before or during the result.

Notes:
- The system automatically injects the user's user_id; pass a placeholder like "auto" for the user_id parameter when calling `get_promotion_materials`.
- The final response MUST include:
  1. An enthusiastic opening, mentioning the current product's commission rate.
  2. Packaging of the product's core selling points.
  3. A clear, exclusive referral link.
  4. The poster URL generated by `generate_ai_poster` displayed using Markdown image syntax (e.g., `![Exclusive Poster](URL)`).

[System-provided user memory / background context]:
{memory_context if memory_context else "No background context available."}
"""
        inner_agent = create_react_agent(
            model=self.llm,
            tools=tools,
            prompt=system_prompt
        )
        
        print("📢 [PromotionAgent] Generating marketing and promotional materials...")
        
        result = await inner_agent.ainvoke(
            {"messages": state["messages"]}, 
            config=config
        )
        
        final_message = result["messages"][-1]
        return {"messages": [final_message]}
